### ISSUE TITLE
Script is not working

### ISSUE THREAD

**Issue by dsamit** [ChaosEvoker/html-to-pdf#7]
Hi,

I was trying to generate pdf from HTML containing some javascript functions which runs on page load.

But it doesn't seems to be working with those javascript codes.

Please help me out that how can i able to run scripts.

Thanks,
Amit

**Comment by ChaosEvoker** [comment]
Since the Java program which renders the HTML into a PDF does not use a headless browser, you may not be able to run scripts with this solution. There are other similar solutions which use a headless browser (like Phantom JS) that might work for your purposes.
